import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { projectBySlug,projects } from "@/data/projects";
import { HiLockClosed } from "react-icons/hi2";
type Props={params:{slug:string}};
export function generateStaticParams(){return projects.map(({slug})=>({slug}))}
export function generateMetadata({params}:Props):Metadata{const p=projectBySlug(params.slug);return p?{title:p.title,description:p.restricted?"Confidential project protected by a non-disclosure agreement.":p.summary}:{}}
export default function ProjectPage({params}:Props){const project=projectBySlug(params.slug);if(!project)notFound();if(project.restricted)return <main id="main-content" className="container-grid grid min-h-screen place-items-center pb-20 pt-28"><section className="max-w-2xl text-center"><HiLockClosed className="mx-auto text-7xl text-signal"/><p className="eyebrow mt-8 text-signal">Protected work · NDA</p><h1 className="balance mt-6 text-4xl font-black tracking-[-.05em] md:text-6xl">{project.title}</h1><p className="mx-auto mt-6 max-w-xl leading-7 text-muted">This project contains confidential information protected by a non-disclosure agreement. Screenshots, implementation details, and the case study are not available for public viewing.</p><Link href="/#work" className="magnetic mt-9 inline-flex rounded-full border border-ink/20 px-6 py-4 text-sm font-black hover:border-signal">← Return to selected work</Link></section></main>;const index=projects.findIndex(p=>p.slug===project.slug);const next=projects[(index+1)%projects.length];return <main id="main-content">
 <header className="container-grid pb-14 pt-32 md:pb-20 md:pt-40"><Link href="/#work" className="text-xs font-black text-muted transition hover:text-signal">← Back to selected work</Link><div className="mt-14 grid gap-10 lg:grid-cols-12"><div className="lg:col-span-8"><p className="eyebrow text-signal">Case study / {project.number}</p><h1 className="balance mt-6 text-5xl font-black leading-[.9] tracking-[-.065em] md:text-8xl">{project.title}</h1></div><div className="flex flex-col justify-end lg:col-span-4"><p className="text-lg leading-8 text-muted">{project.summary}</p></div></div></header>
 <div className="container-grid"><div className="relative aspect-[16/9] overflow-hidden rounded-3xl bg-ash"><Image src={project.image} alt={project.imageAlt} fill priority sizes="(min-width:768px) 90vw,100vw" className="object-contain p-3 md:p-8"/></div><dl className="grid border-b border-ink/15 py-8 sm:grid-cols-2 lg:grid-cols-4">{[["Role",project.role],["Timeline",project.timeline],["Scope",project.scope],["Tools",project.tools]].map(([label,value])=><div key={label} className="border-ink/15 py-4 sm:border-l sm:px-5 first:border-0 first:pl-0"><dt className="eyebrow text-muted">{label}</dt><dd className="mt-3 text-sm font-bold leading-6">{value}</dd></div>)}</dl></div>
 <section className="container-grid py-24 md:py-36"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-signal">01 / The challenge</p></div><div className="lg:col-span-8"><h2 className="balance text-4xl font-black leading-[1.05] tracking-[-.045em] md:text-6xl">{project.problem}</h2><ul className="mt-12 grid gap-3 sm:grid-cols-3">{project.constraints.map(item=><li key={item} className="rounded-2xl bg-ash p-5 text-sm leading-6">{item}</li>)}</ul></div></div></section>
 <section className="bg-ink py-24 text-paper md:py-36"><div className="container-grid grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-signal">02 / Product thinking</p></div><div className="lg:col-span-8"><blockquote className="balance text-3xl font-black leading-[1.1] tracking-[-.04em] md:text-6xl">“{project.insight}”</blockquote><p className="mt-10 border-l-2 border-signal pl-5 text-lg leading-8 text-paper/65">{project.direction}</p></div></div></section>
 <section className="container-grid py-24 md:py-36"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-signal">03 / Key decisions</p></div><div className="lg:col-span-8">{project.decisions.map((d,i)=><article key={d.decision} className="grid gap-5 border-t border-ink/15 py-10 sm:grid-cols-[4rem_1fr]"><span className="text-3xl font-black text-signal">0{i+1}</span><div><h2 className="text-2xl font-black tracking-tight">{d.decision}</h2><p className="mt-4 leading-7 text-muted">{d.mattered}</p><p className="mt-5 text-sm font-bold">Result: {d.changed}</p></div></article>)}</div></div></section>
 <section className="border-y border-ink/15 bg-ash/50 py-24 md:py-32"><div className="container-grid grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-signal">04 / Outcome</p></div><div className="lg:col-span-8"><strong className="text-5xl font-black tracking-[-.06em] text-signal md:text-8xl">{project.result}</strong><p className="mt-6 max-w-2xl text-xl leading-8">{project.resultLabel}.</p><p className="mt-10 max-w-2xl border-t border-ink/15 pt-6 leading-7 text-muted">{project.reflection}</p></div></div></section>
 <Link href={`/projects/${next.slug}`} className="group block bg-ink py-16 text-paper transition hover:bg-signal hover:text-[#071009]"><div className="container-grid flex items-end justify-between gap-8"><div><p className="eyebrow opacity-55">Next project</p><h2 className="mt-5 max-w-4xl text-3xl font-black tracking-[-.04em] md:text-6xl">{next.title}</h2></div><span className="text-4xl transition group-hover:translate-x-2">→</span></div></Link>
 </main>}
