"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { HiLockClosed } from "react-icons/hi2";
import { projects } from "@/data/projects";

export function ProjectIndex(){const sectionRef=useRef<HTMLElement>(null);const[entered,setEntered]=useState(false);useEffect(()=>{const node=sectionRef.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>setEntered(entry.isIntersecting),{threshold:0,rootMargin:"0px 0px -12% 0px"});observer.observe(node);return()=>observer.disconnect()},[]);return <section ref={sectionRef} id="work" className={"project-index relative scroll-mt-20 overflow-hidden border-y border-ink/10 py-24 md:py-36 "+(entered?"is-visible":"")}><div className="project-curtain pointer-events-none absolute inset-0 z-30 grid grid-cols-4" aria-hidden="true">{[0,1,2,3].map(index=><i key={index} style={{transitionDelay:(index*90)+"ms"}}/>)}</div><div className="container-grid relative z-10">
 <div className="project-heading grid gap-8 border-b border-ink/15 pb-9 lg:grid-cols-12"><div className="lg:col-span-3"><p className="eyebrow text-signal">04 / Selected work</p></div><div className="lg:col-span-6"><h2 className="text-4xl font-black leading-[.95] tracking-[-.055em] md:text-6xl">Selected web projects.</h2></div><p className="max-w-xs text-sm leading-6 text-muted lg:col-span-3 lg:self-end">Applications and systems built around real workflows and user needs.</p></div>
 <div className="project-grid mt-10 grid border-t border-ink/15 sm:grid-cols-2 xl:grid-cols-4">{projects.map((project,index)=>{const content=<article style={{"--project-delay":(index*110)+"ms"} as CSSProperties} className="project-column group flex h-full flex-col border-b border-ink/15 p-5 sm:border-r xl:min-h-[34rem]">
  <div className="flex items-center justify-between"><span className="font-mono text-[10px] font-bold text-signal">PROJECT 0{index+1}</span><span className="font-mono text-[9px] text-muted">{project.year}</span></div>
  <div className="relative mt-5 aspect-[4/3] overflow-hidden bg-ash">{project.restricted?<div className="absolute inset-0 grid place-items-center bg-[#151715] text-center text-white"><div><HiLockClosed className="mx-auto text-3xl text-signal"/><p className="mt-4 text-[9px] font-black uppercase tracking-[.18em]">Protected by NDA</p></div></div>:<Image src={project.image} alt={project.imageAlt} fill sizes="(min-width:1280px) 23vw,(min-width:640px) 48vw,100vw" className="object-contain p-3 transition duration-700 group-hover:scale-[1.035]"/>}</div>
  <div className="flex flex-1 flex-col pt-6"><p className="eyebrow text-muted">{project.role}</p><h3 className="mt-4 text-2xl font-black leading-[1.05] tracking-[-.035em]">{project.title}</h3><p className="mt-5 line-clamp-3 text-sm leading-6 text-muted">{project.restricted?"Confidential development work. Public screenshots and implementation details are withheld.":project.summary}</p><div className="mt-auto flex items-center justify-between pt-7"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-muted">{project.category}</span><span className="grid size-9 place-items-center rounded-full border border-ink/15 transition group-hover:border-signal group-hover:bg-signal group-hover:text-[#08100a]">{project.restricted?<HiLockClosed/>:"↗"}</span></div></div>
 </article>;return project.restricted?<div key={project.slug} aria-label={project.title+" is protected by NDA"}>{content}</div>:<Link key={project.slug} href={"/projects/"+project.slug} aria-label={"Read "+project.title+" case study"}>{content}</Link>})}</div>
 </div></section>}
